name: "@ubiquity-os-marketplace/text-vector-embeddings"
description: "Store vector embeddings for issue comments and enable similarity queries."

inputs:
  stateId:
    description: "State Id"
  eventName:
    description: "Event Name"
  eventPayload:
    description: "Event Payload"
  settings:
    description: "Settings"
  authToken:
    description: "Auth Token"
  ref:
    description: "Ref"
  signature:
    description: "Signature sent from the Kernel"
  command:
    description: "Command"

runs:
  using: "composite"
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v2

    - name: Execute plugin
      shell: bash
      run: deno run --unstable-sloppy-imports --allow-all --unstable-kv dist/index.js
      env:
        PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        VOYAGEAI_API_KEY: ${{ secrets.VOYAGEAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
        DENO_KV_URL: ${{ secrets.DENO_KV_URL }}
        DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
