name: "Plugin Compute"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "Signature tp identify the Kernel"
      command:
        description: "Command"

jobs:
  compute:
    name: "Comment Embedding Store"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && 'main' || 'development' }}
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      VOYAGEAI_API_KEY: ${{secrets.VOYAGEAI_API_KEY}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
      DENO_KV_URL: ${{ secrets.DENO_KV_URL }}
      DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2

      - name: Execute plugin
        run: deno run --unstable-sloppy-imports --allow-all --unstable-kv dist/index.js
        env:
          PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          VOYAGEAI_API_KEY: ${{secrets.VOYAGEAI_API_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
          DENO_KV_URL: ${{ secrets.DENO_KV_URL }}
          DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
